---
#To run this script 
#1-use the rhvh host which has ansible already installed
#2-Create a .inventory file with following command (change the hostname to mathc RHVM Server)
#cat > .inventory << EOF
#[hosts]
#rhvm.myhost.com
#EOF
#
#3-Then create a password file (not vaulted!) with following command
#cat > ovirt_variables.yml << EOF
#RHVMURL: "https://rhvm.myhost.com/ovirt-engine/api"
#RHVMUser: "admin@internal"
#RHVMPass: "ahoora"
#VMName: "myvm01"
#VMComment: "My VM Comments"
#VMDescription: "VM Description"
#VMTimeZone: "Asia/Tehran"
#VMMemory: "2GiB"
#VMSocket: 2
#VMCore: 2
#VMOS: rhel_8x64
#VMDiskSize: 10GiB
#VMStorageDomain: hosted_storage
#VMNetProfile: ovirtmgmt
#VMNetNetwork: ovirtmgmt
###########################
#ImageName: rhel-8.3-x86_64
#ImagePath: /root/images/rhel-8.3-x86_64-kvm.qcow2
#VMTempate: RHEL8.3Template
#
#
#EOF
#
#4-Manually change the hostname and password in above files to match your requirements
#5-Run the commands below on rhvh host to send public key to rhvm host
#ssh-copy-id -i .ssh/id_rsa.pub rhvm.myhost.com
#scp rhvm:/etc/pki/ovirt-engine/ca.pem ~/
#Then run the following command
#ansible-playbook -i .inventory create-barevm-v1.yml
- name: Create a standard VM with no image
  hosts: rhvm.myhost.com
  tasks:
  - include_vars: ovirt_variables.yml

  - name: Obtain SSO token with using username/password credentials
    ovirt_auth:
      url: "{{ RHVMURL }}"
      username: "{{ RHVMUser }}"
      ca_file: /etc/pki/ovirt-engine/ca.pem
      password: "{{ RHVMPass }}"


  - ovirt_vm:
      auth: "{{ ovirt_auth }}"
      state: present
      cluster: Default
      name: "{{ VMName }}"
      comment: "{{ VMComment }}"
      description: "{{ VMDescription }}"
      timezone: "{{ VMTimeZone }}"
      soundcard_enabled: no
      memory: "{{ VMMemory }}"
      cpu_cores: "{{ VMCore }}"
      cpu_sockets: "{{ VMSocket }}"
      type: server
      operating_system: "{{ VMOS }}"
      nics:
        - name: nic1

  - ovirt_disk:
      auth: "{{ ovirt_auth }}"
      name: "{{ VMName }}-disk"
      vm_name: "{{ VMName }}"
      size: "{{ VMDiskSize }}"
      format: cow
      bootable: yes
      interface: virtio_scsi
      storage_domain: "{{ VMStorageDomain }}"

  - ovirt_nic:
      auth: "{{ ovirt_auth }}"
      state: present
      vm: "{{ VMName }}"
      name: nic1
      interface: virtio
      profile: "{{ VMNetProfile }}"
      network: "{{ VMNetNetwork }}"


...

