---
- name: test ansible playbook
  hosts: rhvm.myhost.com
  tasks:
  - include_vars: ovirt_password.yml

  - name: Obtain SSO token with using username/password credentials
    ovirt_auth:
      url: https://rhvm.myhost.com/ovirt-engine/api
      username: admin@internal
      ca_file: /etc/pki/ovirt-engine/ca.pem
      password: "{{ ovirt_password }}"


  - ovirt_vm:
      auth: "{{ ovirt_auth }}"
      state: present
      cluster: Default
      name: myvm
      comment: myvm comment
      description: myvm Description
      timezone: Asia/Tehran
      soundcard_enabled: no
      memory: 2GiB
      cpu_cores: 2
      cpu_sockets: 2
      cpu_shares: 1024
      type: server
      operating_system: rhel_7x64
      nics:
        - name: nic1

  - ovirt_disk:
      auth: "{{ ovirt_auth }}"
      name: myvm_disk
      vm_name: myvm
      size: 10GiB
      format: cow
      bootable: yes
      interface: virtio_scsi
      storage_domain: hosted_storage

  - ovirt_nic:
      auth: "{{ ovirt_auth }}"
      state: present
      vm: myvm
      name: nic1
      interface: virtio
      profile: ovirtmgmt
      network: ovirtmgmt


...
