---
#To run this script please refer to the create-barevm-v1.yml file for descriptions
- name: Create Ovirt VM based on a cow template
  hosts: rhvh01.myhost.com
  tasks:
  - include_vars: ovirt_variables.yml

  - name: Obtain SSO token with using username/password credentials
    ovirt_auth:
      url: "{{ RHVMURL }}"
      username: "{{ RHVMUser }}"
      ca_file: ca.pem
      password: "{{ RHVMPass }}"


  - ovirt_vm:
      auth: "{{ ovirt_auth }}"
      cluster: Default
      name: "{{ VMName }}"
      comment: "{{ VMComment }}"
      description: "{{ VMDescription }}"
      template: "{{ VMTempate }}"
      memory: "{{ VMMemory }}"
      cpu_cores: "{{ VMCore }}"
      cpu_sockets: "{{ VMSocket }}"
      type: server
      state: running
      operating_system: "{{ VMOS }}"
      nics:
        - name: nic1

...

